package com.itshare.exceptions.example4;

public class Main {

	
	public static void main ( String[] args) {
		
		try {
		Calculator cal = new Calculator();
		int x   = cal.divide(2, 0);
		System.out.println(x);
		}catch(Exception ex){
			System.out.println("eror");
		}
		
}
	
}
